"use client";

import { useEffect, useState } from "react";
import AdminLayout, { adminFetch } from "../../../components/AdminLayout";
import DataTable from "../../../components/DataTable";

export default function AdminUsersPage() {
  const [users, setUsers] = useState([]); const [colleges, setColleges] = useState([]); const [filters, setFilters] = useState({ search: "", role: "", collegeId: "" }); const [status, setStatus] = useState({ loading: true, error: "", success: "" });
  async function load() { setStatus({ loading: true, error: "", success: "" }); try { const query = new URLSearchParams({ limit: "10", ...(filters.search ? { search: filters.search } : {}), ...(filters.role ? { role: filters.role } : {}), ...(filters.collegeId ? { collegeId: filters.collegeId } : {}) }); const body = await adminFetch(`/api/admin/users?${query}`); setUsers(body.users || []); setStatus({ loading: false, error: "", success: "" }); } catch (error) { setStatus({ loading: false, error: error.message, success: "" }); } }
  useEffect(() => { adminFetch("/api/admin/colleges").then((body) => setColleges(body.colleges || [])).catch(() => {}); }, []);
  useEffect(() => { load(); }, []);
  async function updateRole(id, role) { try { await adminFetch(`/api/admin/users/${id}/role`, { method: "PATCH", body: JSON.stringify({ role }) }); setStatus({ loading: false, error: "", success: "Role updated." }); await load(); } catch (error) { setStatus({ loading: false, error: error.message, success: "" }); } }
  return <AdminLayout title="Users"><form onSubmit={(event) => { event.preventDefault(); load(); }}><input aria-label="Search name or email" placeholder="Search name or email" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} /><select aria-label="Role filter" value={filters.role} onChange={(event) => setFilters({ ...filters, role: event.target.value })}><option value="">All roles</option><option value="student">Student</option><option value="faculty">Faculty</option><option value="admin">Admin</option></select><select aria-label="College filter" value={filters.collegeId} onChange={(event) => setFilters({ ...filters, collegeId: event.target.value })}><option value="">All colleges</option>{colleges.map((college) => <option key={college._id} value={college._id}>{college.name}</option>)}</select><button type="submit">Search</button></form>{status.loading && <p>Loading users...</p>}{status.error && <p role="alert">{status.error}</p>}{status.success && <p role="status">{status.success}</p>}{!status.loading && !status.error && <DataTable rows={users} columns={[{ key: "name", label: "Name" }, { key: "email", label: "Email" }, { key: "role", label: "Role", render: (user) => <select value={user.role} aria-label={`Role for ${user.email}`} onChange={(event) => updateRole(user._id, event.target.value)}><option value="student">Student</option><option value="faculty">Faculty</option><option value="admin">Admin</option></select> }]} empty="No users match these filters." />}</AdminLayout>;
}
